# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Notification De Stock"
client_id = "3ed45186bd7cce0a10131ac4962988fb"
application_url = "https://loads-socket-jessica-put.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://loads-socket-jessica-put.trycloudflare.com/auth/callback",
  "https://loads-socket-jessica-put.trycloudflare.com/auth/shopify/callback",
  "https://loads-socket-jessica-put.trycloudflare.com/api/auth/callback",
  "https://loads-socket-jessica-put.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "starliner21-venum.myshopify.com"
