# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1b9f8ecc3d66a51c9bbfcc18368dfb8b"
name = "notification-de-stock"
application_url = "https://disabled-cakes-parents-exclusively.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "starliner21-venum.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_products,write_products"

[auth]
redirect_urls = [
  "https://disabled-cakes-parents-exclusively.trycloudflare.com/auth/callback",
  "https://disabled-cakes-parents-exclusively.trycloudflare.com/auth/shopify/callback",
  "https://disabled-cakes-parents-exclusively.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
